(DEFINE (remove_last L)
        (IF (= (LENGTH L) 1) (CAR L)
            (remove_last (CDR L))
            )
        )

(DEFINE (inner_list L)
        ;(IF (NULL? (CAR L)) (CAR L) (inner_list (CDR L)))
        ;(CAR (CDR L))
        (COND ((LIST? (CAR L))
               (CAR L))
              (ELSE (inner_list (CDR L)))
              )
        )