(DEFINE (remove_last L)
        (IF (= (LENGTH L) 1) (CAR L)
            (remove_last (CDR L))
            )
        )

(DEFINE (inner_list L)
        ;(IF (NULL? (CAR L)) (CAR L) (inner_list (CDR L)))
        ;(CAR (CDR L))
        (COND ((LIST? (CAR L))
               (CAR L))
              (ELSE (inner_list (CDR L)))
              )
        )

(DEFINE (reverse_general L)
        (COND ((NULL? L) '())
              ((LIST? L)
               (append (reverse_general (CDR L))
                       (LIST (reverse_general (CAR L)))
                       )
               )
              (ELSE L)
              )
        )

               